### ISSUE TITLE
using TableDependency.Mappers;

### ISSUE THREAD

**Issue by masoudsharifipour** [christiandelbianco/monitor-table-change-with-mvc-signalR-jquery-sqltabledependency#1]
using TableDependency.Mappers;            Using NotFound ?? 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Mappers' does not exist in the namespace 'TableDependency' (are you missing an assembly reference?)	SQL Server Notifications SignalR	E:\Project\NotfiacationSQLServer\SQL Server Notifications SignalR\SQL Server Notifications SignalR\SQL Server Notifications SignalR\SignalR.Sample\StockTicker.cs	10	Active

**Comment by christiandelbianco** [comment]
Hi, Mappers is part of the TableDependency dll that you need to install with SqlTableDependency.

**Comment by masoudsharifipour** [comment]
Please see attached images.



![erorr](https://user-images.githubusercontent.com/14156696/27877999-ff858402-61d1-11e7-942b-bc23cfe79a2d.png)
![erorr1](https://user-images.githubusercontent.com/14156696/27878000-ff8b7344-61d1-11e7-9a71-0bec54e5d128.png)

**Comment by masoudsharifipour** [comment]
using TableDependency.Mappers; Using NotFound ??

**Comment by christiandelbianco** [comment]
Hi
I checked the code. If you hve latest version of SqlTableDepdendency ( 6.1.0 ), you can **remove** this line:

using TableDependency.Mappers;

It does not need anymore, as ModelToTableMapper class is not in the "root" namespace.

**Comment by masoudsharifipour** [comment]
Thank you guys
The problem was solved


`            var mapper = new TableDependency.ModelToTableMapper<Stock>();
            mapper.AddMapping(s => s.Symbol, "Code");

            _tableDependency = new SqlTableDependency<Stock>(
                ConfigurationManager.ConnectionStrings["connectionString"].ConnectionString,
                "Stocks",
                mapper);
`

**Comment by christiandelbianco** [comment]
GOOD!

**Comment by help-needer** [comment]
@christiandelbianco sir. Am getting this error "cannot convert from 'TableDependency.ModelToTableMapper<FlightBooking.Models.FlightAvailability>' to 'string'"

![report](https://user-images.githubusercontent.com/41954292/43457453-884853a0-94e4-11e8-8779-6acfe854ee09.png)

help me sir!

**Comment by christiandelbianco** [comment]
Use constructor parameter name before parameter value:

, mapper **:** _yourmapper_

**Comment by help-needer** [comment]
[https://www.youtube.com/watch?v=FBkkdCuTO7g](url)

@christiandelbianco  Sir, am just doing the same (FlightBooking) project by watching your tutorial. First of all thanks for the very useful tutorial. Am new to this concept and am not sure what is the constructor name in our FlightBookingService.cs . 

`private readonly static Lazy<FlightBookingService> _instance = new Lazy<FlightBookingService>(() => new FlightBookingService(GlobalHost.ConnectionManager.GetHubContext<FlightBookingHub>().Clients));
        private SqlTableDependency<FlightAvailability> SqlTableDependency { get; }
        private IHubConnectionContext<dynamic> Clients { get; }

        #endregion

        #region Constructors
        //My code
        private FlightBookingService(IHubConnectionContext<dynamic> clients)
        {
            this.Clients = clients;

            // Because our C# model has a property not matching database table name, an explicit mapping is required just for this property.
            var mapper = new ModelToTableMapper<FlightAvailability>();
            mapper.AddMapping(x => x.Availability, "SeatsAvailability");

            // Because our C# model name differs from table name we have to specify database table name.
            this.SqlTableDependency = new SqlTableDependency<FlightAvailability>(ConfigurationManager.ConnectionStrings["connectionString"].ConnectionString, "FlightBookings", mapper:"mapper");
            this.SqlTableDependency.OnChanged += this.TableDependency_OnChanged;
            this.SqlTableDependency.Start();
        }`


> Use constructor parameter name before parameter value:

, mapper : yourmapper

I can't understand your answer sir. i don't know how to do this. So kindly send your answer as code

**Comment by help-needer** [comment]
@christiandelbianco  Sir, am just doing the same (FlightBooking) project by watching your tutorial. First of all thanks for the very useful tutorial. Am new to this concept and am not sure what is the constructor name in our FlightBookingService.cs .

`private FlightBookingService(IHubConnectionContext<dynamic> clients)
        {
            this.Clients = clients;

            // Because our C# model has a property not matching database table name, an explicit mapping is required just for this property.
            var mapper = new ModelToTableMapper<FlightAvailability>();
            mapper.AddMapping(x => x.Availability, "SeatsAvailability");

            // Because our C# model name differs from table name we have to specify database table name.
            this.SqlTableDependency = new SqlTableDependency<FlightAvailability>(ConfigurationManager.ConnectionStrings["connectionString"].ConnectionString, "FlightBookings", mapper);
            this.SqlTableDependency.OnChanged += this.TableDependency_OnChanged;
            this.SqlTableDependency.Start();
        }`

Kindly Correct my mistake sir. Thanks in advance Sir :)

**Comment by PolloKulos** [comment]
Hi, take your example, but do not send me error of any. I followed step by step, and I can not connect to sql server.
