### ISSUE TITLE
I cannot find a database table named 'Data'

### ISSUE THREAD

**Issue by proovit** [christiandelbianco/monitor-table-change-with-mvc-signalR-jquery-sqltabledependency#2]
Hi,

The table is in a namespace: [Application.Data.SC].[Demands]
I tried several things, but always get the same, "I cannot find a database table named..."
dbo tables are being found.
What should I do?

**entity code:**
    <Table("[Application.Data.SC].Demands")>
    Partial Public Class Demand
                ....

**Code:**
Dim str_Table As String = "[Application.Data.SC].[Demands]"
= New TableDependency.SqlClient.SqlTableDependency(Of Models.ScoreCard.Demand)(mobj_Settings.ScoreCard_Database_ConnectionString, str_Table)

**Comment by christiandelbianco** [comment]
hi, if you need to define your namespace differente from DBO, you must use:

[Table("Customers", Schema = "test_schema")]

Please have a look at this test class:
TableDependency.SqlClient.Test.UseSchemaOtherThanDboTestSqlServer.cs
