### ISSUE TITLE
Why do you use singleton for StockTicker

### ISSUE THREAD

**Issue by kanachrisi** [christiandelbianco/monitor-table-change-with-mvc-signalR-jquery-sqltabledependency#3]
Hello Christian,
I have a question regarding the implementation of StockTicker class. 
I don't really understand the reasons of using singleton in StockTicker class.
Could please give some reasons that made you choose that pattern ?
BTW thank you a lot for this wonderfull plugin, it solved the problem that i had with SqlDependency.

**Comment by christiandelbianco** [comment]
I copied that example from Microsoft.
So, i cannot explain why.

**Comment by kanachrisi** [comment]
Do you remember which document copied from (Microsoft Documentation) ?
Thanks
